/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EBlist</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.EBlist#getLe <em>Le</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getEBlist()
 * @model
 * @generated
 */
public interface EBlist extends EObject
{
  /**
   * Returns the value of the '<em><b>Le</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Le</em>' containment reference.
   * @see #setLe(LExpr)
   * @see pret.myDsl.MyDslPackage#getEBlist_Le()
   * @model containment="true"
   * @generated
   */
  LExpr getLe();

  /**
   * Sets the value of the '{@link pret.myDsl.EBlist#getLe <em>Le</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Le</em>' containment reference.
   * @see #getLe()
   * @generated
   */
  void setLe(LExpr value);

} // EBlist
