/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.For#getExp <em>Exp</em>}</li>
 *   <li>{@link pret.myDsl.For#getFocom <em>Focom</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getFor()
 * @model
 * @generated
 */
public interface For extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see pret.myDsl.MyDslPackage#getFor_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link pret.myDsl.For#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

  /**
   * Returns the value of the '<em><b>Focom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Focom</em>' containment reference.
   * @see #setFocom(Commands)
   * @see pret.myDsl.MyDslPackage#getFor_Focom()
   * @model containment="true"
   * @generated
   */
  Commands getFocom();

  /**
   * Sets the value of the '{@link pret.myDsl.For#getFocom <em>Focom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Focom</em>' containment reference.
   * @see #getFocom()
   * @generated
   */
  void setFocom(Commands value);

} // For
