/**
 * generated by Xtext 2.25.0
 */
package pret.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pret.myDsl.Model#getProgramme <em>Programme</em>}</li>
 * </ul>
 *
 * @see pret.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Programme</b></em>' containment reference list.
   * The list contents are of type {@link pret.myDsl.Program}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Programme</em>' containment reference list.
   * @see pret.myDsl.MyDslPackage#getModel_Programme()
   * @model containment="true"
   * @generated
   */
  EList<Program> getProgramme();

} // Model
